// Phase 0 placeholder — full code-gen lives in Phase 5 per plan.md §Phase 5.
// Reads src/style/themes/*.css, emits src/src/theme/themes.rs. For now writes
// a one-line placeholder so the workspace member compiles and Trunk's
// pre-build hook has a target to invoke.

use std::fs;
use std::path::Path;

fn main() -> std::io::Result<()> {
    // Resolve output path relative to the workspace root (CARGO_MANIFEST_DIR
    // is .../tools/build-themes when invoked via `cargo run -p`).
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let workspace_root = Path::new(manifest_dir)
        .ancestors()
        .nth(2)
        .expect("workspace root above tools/build-themes");
    let theme_dir = workspace_root.join("src").join("src").join("theme");
    let theme_file = theme_dir.join("themes.rs");

    fs::create_dir_all(&theme_dir)?;
    fs::write(
        &theme_file,
        "// Generated by tools/build-themes/. DO NOT EDIT (Phase 0 placeholder).\n",
    )?;

    Ok(())
}
