// Theme catalogue code-gen — Phase 5 (T220) of spec
// 001-leptos-migration. Reads `<workspace>/src/style/themes/*.css`,
// emits `<workspace>/src/src/theme/themes.rs` with the catalogue
// surfaced as a `pub const ALL_THEMES: &[&str]` slice and a
// `pub const DEFAULT_THEME: &str` constant. The Trunk pre-build
// hook (`src/Trunk.toml` `[[hooks]]` stage = `pre_build`) invokes
// the binary on every `trunk serve` / `trunk build`, so the
// Settings → Theme tab and the loader (`src/src/theme/loader.rs`)
// always see the live filesystem catalogue without a manual list.
//
// Mirrors the JS-era `build-themes.js` discovery script and the
// `theme-loader.js::discoverThemeFiles` whitelist. Per FR-021 the
// rendered theme contract is preserved.
//
// Per AGENTS.md §"Phoenix/Elixir coding guidelines" — N/A here;
// this is a workspace-internal Rust build tool. The lints inherit
// from the workspace `[lints]` table (pedantic + nursery deny).

use std::fs;
use std::io;
use std::path::Path;

/// Scan `input_dir` for `*.css` files (excluding hidden files —
/// names starting with `.`), derive the alphabetised stem list,
/// and write the generated `themes.rs` to `output_path`.
///
/// Returns the number of themes discovered. Emits an empty
/// catalogue (`ALL_THEMES: &[&str] = &[]`,
/// `DEFAULT_THEME: &str = ""`) when the directory is missing or
/// contains no CSS files — the binary is invoked from a Trunk
/// pre-build hook and silently producing an empty catalogue is
/// preferable to crashing the build pre-launch.
///
/// # Errors
/// Propagates `io::Error` from directory iteration / file write
/// failures. The caller (binary entrypoint) prints the error to
/// stderr and exits non-zero so the Trunk hook surfaces the
/// failure.
fn generate_themes_rs(input_dir: &Path, output_path: &Path) -> io::Result<usize> {
    let mut stems: Vec<String> = Vec::new();

    if input_dir.is_dir() {
        for entry in fs::read_dir(input_dir)? {
            let entry = entry?;
            let path = entry.path();
            if !path.is_file() {
                continue;
            }
            let Some(file_name) = path.file_name().and_then(|s| s.to_str()) else {
                continue;
            };
            // Skip hidden files (`.DS_Store`, `.gitkeep`, etc.).
            if file_name.starts_with('.') {
                continue;
            }
            // Only `*.css` participate in the catalogue.
            let Some(stem) = file_name.strip_suffix(".css") else {
                continue;
            };
            if stem.is_empty() {
                continue;
            }
            stems.push(stem.to_owned());
        }
    }

    stems.sort();
    stems.dedup();

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }

    let body = render_themes_rs(&stems);
    fs::write(output_path, body)?;

    Ok(stems.len())
}

/// Render the generated `themes.rs` body. Pure function — no I/O
/// — so the unit test can pin the rendered text shape independent
/// of filesystem state.
fn render_themes_rs(stems: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by tools/build-themes — DO NOT EDIT.\n");
    out.push_str("//\n");
    out.push_str("// Catalogue derived from `<workspace>/src/style/themes/*.css` at\n");
    out.push_str("// every `trunk build` / `trunk serve` (pre_build hook in\n");
    out.push_str("// `src/Trunk.toml`). Re-run `cargo run -p presto-build-themes` to\n");
    out.push_str("// regenerate locally. Spec 001-leptos-migration §Phase 5 (T219-T220).\n");
    out.push('\n');
    out.push_str("/// Alphabetised list of every theme stem (filename without the\n");
    out.push_str("/// `.css` suffix) discovered in `src/style/themes/`. Consumed by\n");
    out.push_str("/// `components::settings::theme::ThemeSettings` to render one\n");
    out.push_str("/// `<button data-timer-theme=\"...\">` per stem.\n");
    out.push_str("pub const ALL_THEMES: &[&str] = &[");
    if !stems.is_empty() {
        out.push('\n');
        for stem in stems {
            out.push_str("    \"");
            out.push_str(stem);
            out.push_str("\",\n");
        }
    }
    out.push_str("];\n");
    out.push('\n');
    out.push_str("/// Default theme applied at first launch. The first stem\n");
    out.push_str("/// alphabetically — empty string when the catalogue is empty.\n");
    out.push_str("pub const DEFAULT_THEME: &str = \"");
    if let Some(first) = stems.first() {
        out.push_str(first);
    }
    out.push_str("\";\n");
    out
}

fn main() -> io::Result<()> {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let workspace_root = Path::new(manifest_dir)
        .ancestors()
        .nth(2)
        .expect("workspace root above tools/build-themes");
    let input_dir = workspace_root.join("src").join("style").join("themes");
    let output_path = workspace_root
        .join("src")
        .join("src")
        .join("theme")
        .join("themes.rs");

    let count = generate_themes_rs(&input_dir, &output_path)?;
    // Single concise stdout line is fine — Trunk's pre_build hook
    // forwards it to the user so the count surfaces during dev.
    // `print_stdout` is workspace-denied; allow with rationale.
    #[allow(
        clippy::print_stdout,
        // Build tools surface progress over stdout by convention; the
        // Trunk pre_build hook captures and forwards this to the dev
        // server output. No alternative logger exists in this binary.
    )]
    {
        println!("presto-build-themes: emitted {count} theme(s) to {}", output_path.display());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{generate_themes_rs, render_themes_rs};
    use std::fs;
    use std::path::PathBuf;

    /// T219 [T:RED]: the build-themes binary scans the configured
    /// theme directory for `*.css` files and emits a `themes.rs`
    /// source that exposes the catalogue as Rust constants
    /// (`ALL_THEMES: &[&str]`, `DEFAULT_THEME: &str`). The
    /// generated file lets the Settings → Theme tab render one
    /// tile per CSS file in `src/style/themes/` without a manual
    /// list. Snapshot-style: assert the emitted text contains the
    /// expected strings rather than diffing whole-file because
    /// formatting drift (rustfmt re-flow, trailing whitespace) is
    /// not part of the contract.
    ///
    /// FR-021 (theme contract preserved). Done-signal: this test
    /// passes; `cargo run -p presto-build-themes` emits a non-empty
    /// `themes.rs` with the expected catalogue derived from the
    /// fixture inputs.
    ///
    /// Fixture: a temp directory populated with three placeholder
    /// CSS files mirroring the JS-era catalogue
    /// (`espresso.css`, `pipboy.css`, `pommodore64.css`) plus one
    /// hidden file (`.DS_Store`-style) that MUST be filtered out.
    #[test]
    fn generates_themes_rs_snapshot() {
        // Use a per-test temp directory rooted under target/ so
        // parallel test runs don't collide. `CARGO_TARGET_TMPDIR`
        // would be ideal but isn't stable for `[[bin]]` test
        // harnesses; fall back to `target/tmp/<test-name>` instead.
        let manifest_dir = env!("CARGO_MANIFEST_DIR");
        let target_tmp = PathBuf::from(manifest_dir)
            .join("..")
            .join("..")
            .join("target")
            .join("tmp")
            .join("build-themes-test-snapshot");
        let _ = fs::remove_dir_all(&target_tmp);
        let input_dir = target_tmp.join("themes");
        fs::create_dir_all(&input_dir).expect("create fixture themes dir");
        for name in ["espresso.css", "pipboy.css", "pommodore64.css"] {
            fs::write(input_dir.join(name), "/* fixture */\n")
                .expect("write fixture css");
        }
        // Hidden / non-CSS files must be filtered out.
        fs::write(input_dir.join(".DS_Store"), "junk").expect("hidden fixture");
        fs::write(input_dir.join("README.md"), "not css").expect("non-css fixture");

        let output_path = target_tmp.join("themes.rs");

        generate_themes_rs(&input_dir, &output_path).expect("generate themes.rs");

        let generated = fs::read_to_string(&output_path).expect("read generated");

        // Header must mark the file as auto-generated so reviewers
        // know not to hand-edit it.
        assert!(
            generated.contains("@generated"),
            "generated themes.rs must carry an @generated marker:\n{generated}",
        );
        assert!(
            generated.contains("DO NOT EDIT"),
            "generated themes.rs must carry a DO NOT EDIT note:\n{generated}",
        );

        // The catalogue must surface as a `pub const ALL_THEMES`
        // slice with each theme stem (no `.css` suffix). The order
        // is alphabetical so the rendered tile order is stable
        // across regenerations.
        assert!(
            generated.contains("pub const ALL_THEMES"),
            "missing ALL_THEMES const in:\n{generated}",
        );
        for stem in ["espresso", "pipboy", "pommodore64"] {
            assert!(
                generated.contains(&format!("\"{stem}\"")),
                "expected \"{stem}\" in generated catalogue:\n{generated}",
            );
        }

        // Hidden / non-CSS fixtures must NOT leak in.
        assert!(
            !generated.contains("DS_Store"),
            "hidden file must not appear in catalogue:\n{generated}",
        );
        assert!(
            !generated.contains("README"),
            "non-css file must not appear in catalogue:\n{generated}",
        );

        // A `DEFAULT_THEME` constant must be present. The picked
        // default is the first alphabetically — "espresso" for the
        // JS-era catalogue. Pin the actual default the generator
        // chose so a future flip to e.g. "pipboy" surfaces as a
        // test diff.
        assert!(
            generated.contains("pub const DEFAULT_THEME"),
            "missing DEFAULT_THEME const in:\n{generated}",
        );
        assert!(
            generated.contains("\"espresso\""),
            "expected DEFAULT_THEME to surface \"espresso\" as the alphabetical-first stem:\n{generated}",
        );
    }

    /// Pure-render test: the rendered body is deterministic when
    /// driven from a fixed stem list. Pins the relative ordering
    /// of the catalogue + default-theme constants so refactors
    /// don't accidentally drop one.
    #[test]
    fn render_themes_rs_emits_alphabetised_catalogue() {
        let stems = vec!["espresso".to_owned(), "pipboy".to_owned()];
        let body = render_themes_rs(&stems);
        let espresso_idx = body.find("\"espresso\"").expect("espresso in body");
        let pipboy_idx = body.find("\"pipboy\"").expect("pipboy in body");
        assert!(
            espresso_idx < pipboy_idx,
            "alphabetical ordering: espresso must precede pipboy:\n{body}",
        );
    }

    /// Empty catalogue is allowed (the binary tolerates a missing
    /// or empty themes dir so first-launch / CI without assets
    /// doesn't fail the Trunk pre-build hook).
    #[test]
    fn render_themes_rs_handles_empty_catalogue() {
        let body = render_themes_rs(&[]);
        assert!(body.contains("pub const ALL_THEMES: &[&str] = &[];"));
        assert!(body.contains("pub const DEFAULT_THEME: &str = \"\";"));
    }
}
