
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async saveSessionData(session: Session) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_session_data", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSessionData() : Promise<Result<Session | null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_session_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveTasks(tasks: Task[]) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_tasks", { tasks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadTasks() : Promise<Result<Task[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_tasks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStatsHistory() : Promise<Result<Session[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_stats_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveDailyStats(session: Session) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_daily_stats", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTrayIcon(timerText: string, isRunning: boolean, sessionMode: TimerMode, currentSession: number, totalSessions: number, modeIcon: string | null) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tray_icon", { timerText, isRunning, sessionMode, currentSession, totalSessions, modeIcon }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTrayMenu(isRunning: boolean, isPaused: boolean, currentMode: TimerMode) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tray_menu", { isRunning, isPaused, currentMode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: Settings) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSettings() : Promise<Result<Settings, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerGlobalShortcuts(shortcuts: ShortcutSettings) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_global_shortcuts", { shortcuts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetAllData() : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_all_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startActivityMonitoring(timeoutSeconds: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_activity_monitoring", { timeoutSeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopActivityMonitoring() : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_activity_monitoring") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateActivityTimeout(timeoutSeconds: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_activity_timeout", { timeoutSeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async enableAutostart() : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_autostart") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disableAutostart() : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disable_autostart") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isAutostartEnabled() : Promise<Result<boolean, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_autostart_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveManualSessions(sessions: ManualSession[]) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_manual_sessions", { sessions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadManualSessions() : Promise<Result<ManualSession[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_manual_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveQuickLogs(quickLogs: QuickLog[]) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_quick_logs", { quickLogs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadQuickLogs() : Promise<Result<QuickLog[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_quick_logs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveDistractions(distractions: Distraction[]) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_distractions", { distractions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadDistractions() : Promise<Result<Distraction[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_distractions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadTags() : Promise<Result<Tag[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveTag(tag: Tag) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_tag", { tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTag(tagId: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_tag", { tagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addSessionTag(sessionTag: SessionTag) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_session_tag", { sessionTag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSessionsXlsx(path: string, sessions: ManualSession[]) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_sessions_xlsx", { path, sessions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSessionsCsv(path: string, sessions: ManualSession[]) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_sessions_csv", { path, sessions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Advanced / debug toggles.
 */
export type AdvancedSettings = { debug_mode?: boolean }
/**
 * Ambient-sound track selection (feature 004).
 * 
 * Closed sum type: eleven variants, one per vendored ambient track
 * plus `None` ("no track selected"). `None` is a first-class
 * variant — not `Option<AmbientSoundType>` and not a string sentinel
 * — so the type system encodes the absence case directly
 * (Principle III). Wire shape is kebab-case strings (`"none"`,
 * `"rain"`, ..., `"white-noise"`, `"wind"`, `"pink-noise"`,
 * `"brown-noise"`, `"binaural"`), mirroring the `StatusBarDisplay`
 * precedent at `:27`.
 */
export type AmbientSoundType = 
/**
 * No track selected — playback is a no-op even when
 * `ambient_sound_enabled = true`. Preserves the user's volume
 * slider value (FR-005 / A11). Wire string `"none"`.
 */
"none" | 
/**
 * Rain loop — vendored at `assets/audio/ambient/rain.wav`.
 */
"rain" | 
/**
 * Fire / crackle loop — vendored at `assets/audio/ambient/fire.wav`.
 */
"fire" | 
/**
 * Library / café ambience — vendored at
 * `assets/audio/ambient/library.wav`.
 */
"library" | 
/**
 * Fan hum — vendored at `assets/audio/ambient/fan.wav`.
 */
"fan" | 
/**
 * Storm — vendored at `assets/audio/ambient/storm.wav`.
 */
"storm" | 
/**
 * White noise — vendored at
 * `assets/audio/ambient/white-noise.wav`. CRITICAL: the
 * multi-word variant — `#[serde(rename_all = "kebab-case")]`
 * emits it as `"white-noise"`, not `"whitenoise"`.
 */
"white-noise" | 
/**
 * Wind — vendored at `assets/audio/ambient/wind.wav`.
 */
"wind" | 
/**
 * Pink noise — vendored at `assets/audio/ambient/pink-noise.wav`.
 * Synthesised via `ffmpeg anoisesrc=color=pink`; perceptually
 * flat across octaves and the noise-colour most cited in
 * cognition / sleep research. Loops seamlessly because the
 * signal is stochastic with no periodic structure.
 */
"pink-noise" | 
/**
 * Brown noise — vendored at
 * `assets/audio/ambient/brown-noise.wav`. Synthesised via
 * `ffmpeg anoisesrc=color=brown`; -6 dB/octave roll-off makes
 * it deeper / less hissy than white. Loops seamlessly.
 */
"brown-noise" | 
/**
 * Binaural beat (40 Hz gamma) — vendored at
 * `assets/audio/ambient/binaural.wav`. Pure 200 Hz / 240 Hz
 * sines, one per channel; the 40 Hz delta is perceived as a
 * beat only when worn on headphones. Loops seamlessly (sine
 * periods align at any integer-second boundary).
 */
"binaural"
/**
 * Appearance / theme preferences.
 * 
 * `theme` is the color-mode preference (`"auto"` / `"light"` /
 * `"dark"`); `timer_theme` is the timer palette stem (e.g.
 * `"espresso"`). Both carry `#[serde(default)]` so pre-widening
 * settings JSONs fill in the JS-era cold-start values.
 * 
 * `locale` (feature 005) is `Option<Locale>` — `None` = "user has
 * never explicitly chosen a locale" (legacy records or fresh install
 * — the resolver runs OS detection on cold start); `Some(Locale)` =
 * "user explicitly chose this locale" (including English — bypasses
 * OS detection per FR-011 / Fix A). The `Option` discriminant is the
 * authoritative "explicit vs. default" signal; value-equality against
 * `Locale::En` MUST NOT be used as a proxy.
 */
export type AppearanceSettings = { theme?: string; timer_theme?: string; 
/**
 * Feature 005: user-selected UI locale. `None` = no explicit
 * choice yet; `Some(_)` = explicit choice (any variant, including
 * `Some(En)`). The `Option` discriminant is the resolver's
 * authoritative "explicit vs. default" signal per FR-009 / FR-011.
 * 
 * Lenient deserialisation: an out-of-set wire value (`"fr"`,
 * `42`, etc.) degrades silently to `None` rather than failing the
 * whole-struct parse. Spec Story 2 AC 4 requires that an unknown
 * locale code in a hand-edited settings.json must NOT brick the
 * settings load — the resolver then falls back to OS detection.
 * The `Locale` enum itself remains strict on its own
 * deserialisation surface; only this field is forgiving (two
 * separate contracts).
 */
locale?: Locale | null }
/**
 * Typed error variant returned by every bridge command wrapper.
 * 
 * Wire form is externally-tagged JSON (the `kind` discriminator carries the
 * variant name; data fields sit alongside it).
 */
export type BridgeError = 
/**
 * `window.__TAURI_INTERNALS__` is absent (vite/trunk dev server, e2e
 * mock context). Never produced by the Tauri handler — the Leptos
 * wrapper short-circuits with this variant before calling `invoke()`.
 * Per AGENTS.md §Bridge availability and FR-009.
 */
{ kind: "bridge_unavailable" } | 
/**
 * The caller is in a state where the command is invalid (reserved
 * for future auth-gated paths; no current producer).
 */
{ kind: "not_authenticated" } | 
/**
 * An argument failed validation at the boundary.
 */
{ kind: "invalid_argument"; field: string; reason: string } | 
/**
 * The requested file, key, or row does not exist.
 */
{ kind: "not_found"; resource: string } | 
/**
 * `serde-wasm-bindgen` (or `serde_json`) failed to deserialise the
 * command return on the Leptos side.
 * 
 * Note: data-model.md §`BridgeError` originally specified
 * `command: &'static str` to dodge a per-call allocation, but that
 * makes the enum's `Deserialize` impl require `'de: 'static`, which
 * breaks deserialising any non-static input (e.g., from `from_str`
 * of a heap-allocated JSON buffer). The variant is owning so a
 * `BridgeError` round-trips through serde for every possible
 * discriminant. Allocations are minor (one short literal per failure
 * path; this is the error path, not the hot path).
 */
{ kind: "serde_roundtrip"; command: string; error: string } | 
/**
 * Catch-all for unexpected Tauri-side failures (filesystem errors,
 * plugin errors, etc.). The Tauri-side mapping defaults to this
 * variant for any `.map_err(|e| e.to_string())` call site that
 * lacks semantic context (per data-model.md §`BridgeError` mapping
 * strategy).
 */
{ kind: "internal"; msg: string }
/**
 * User-entered distraction note, optionally tied to the parent
 * session that was running when the note was captured.
 */
export type Distraction = { 
/**
 * UUID v4 string.
 */
id: string; 
/**
 * User-provided. 1..=120 UTF-8 chars. PII — never log in plain.
 */
note: string; 
/**
 * ISO-8601 UTC. Modal-submit time for in-session captures;
 * user-set or `now()` for retroactive entries.
 */
createdAt: string; 
/**
 * chrono `%a %b %d %Y`. Matches the `ManualSession.date`
 * precedent.
 */
date: string; 
/**
 * Snapshotted at modal-open time (per spec Clarifications +
 * Edge Cases). `None` for retroactive entries from Inventory.
 */
parentRef?: DistractionParentRef | null }
/**
 * Snapshot of the parent session at the moment the Distraction modal was opened.
 * 
 * Title is rendered as-snapshotted (never re-resolved); tag is
 * re-resolved against the current tag table at render time
 * (FR-024a).
 */
export type DistractionParentRef = { 
/**
 * ISO-8601 — when the parent session started.
 */
parentSessionStartTs: string; 
/**
 * The running mode at modal-open.
 */
parentMode: TimerMode; 
/**
 * The selected tag id at modal-open. `None` if no tag was set.
 */
parentTagId: string | null; 
/**
 * The session title at modal-open. `None` if not set.
 */
parentTitle: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * User-selectable UI locale (feature 005).
 * 
 * Closed four-variant sum type. Wire shape is lowercase strings
 * (`"en"` / `"de"` / `"it"` / `"tr"`) matching the existing `theme`
 * field's lowercase convention at `:121-123` rather than the
 * `AmbientSoundType` kebab-case precedent — two-letter ISO-639-1
 * codes have no internal word boundary that kebab-case would clarify.
 * 
 * The `#[default]` attribute on `En` ties this enum to
 * `#[derive(Default)]`; the default value is used by `Locale::default()`
 * callers (e.g. the resolver's terminal fallback) — NOT by the
 * `AppearanceSettings.locale` field, which uses `Option<Locale>` so
 * `None` (no explicit choice) and `Some(Locale::En)` (explicit
 * English) are distinguishable per Fix A.
 */
export type Locale = 
/**
 * English — wire string `"en"`. Source-of-truth locale per Spec A13.
 */
"en" | 
/**
 * Deutsch — wire string `"de"`.
 */
"de" | 
/**
 * Italiano — wire string `"it"`.
 */
"it" | 
/**
 * Türkçe — wire string `"tr"`.
 */
"tr"
/**
 * User-entered manual session record.
 * 
 * `session_type` is the closed-domain `SessionType` (was a
 * stringly-typed `String` pre-cutover per spec 001 T029).
 */
export type ManualSession = { id: string; session_type: SessionType; 
/**
 * Minutes.
 */
duration: number; 
/**
 * `HH:MM`.
 */
start_time: string; 
/**
 * `HH:MM`.
 */
end_time: string; notes: string | null; 
/**
 * ISO-8601.
 */
created_at: string; 
/**
 * `%a %b %d %Y`.
 */
date: string; 
/**
 * Inline tag objects per the existing JS-era on-disk shape
 * (FR-005). Loosely typed because legacy records embed full tag
 * objects rather than ID-only references; we normalise at
 * consumption time without reshaping on disk.
 */
tags: JsonValue[] | null; 
/**
 * User-typed session title (≤120 user-perceived chars). Captured
 * at manual-backfill submit time and at natural focus completion
 * (the synth path that mirrors today's auto-saved row into the
 * calendar). Empty-string is forbidden — normalised to `None` at
 * the capture boundary per Principle III.
 */
title?: string | null }
/**
 * Notification preferences.
 * 
 * `auto_start_focus` and `allow_continuous_sessions` carry
 * `#[serde(default)]` because they were added after the `0.4.0`
 * settings shape and may be missing from older settings JSONs.
 * 
 * `clippy::struct_excessive_bools` is silenced because every bool
 * maps to an independent UI toggle; collapsing them into a state
 * machine would not match the on-disk JSON or the settings UI.
 */
export type NotificationSettings = { desktop_notifications: boolean; sound_notifications: boolean; auto_start_timer: boolean; auto_start_focus?: boolean; allow_continuous_sessions?: boolean; smart_pause: boolean; 
/**
 * Seconds.
 */
smart_pause_timeout: number; 
/**
 * When true, fire a soft tick once per second during focus
 * sessions, in sync with the 1 Hz countdown. Default `false`
 * (opt-in per Principle II). UI-side side effect only — engine
 * is unaware. Locked to the second; not user-configurable.
 */
metronome?: boolean; 
/**
 * Feature 004: when true AND `ambient_sound_type != None`
 * AND the timer is in the focus running state, the selected
 * ambient track loops at the configured volume. Default `false`
 * (opt-in per Principle II). UI-side side effect only — engine
 * is unaware.
 */
ambient_sound_enabled?: boolean; 
/**
 * Feature 004: currently-selected ambient track. `None` is a
 * first-class "no track selected" sentinel (FR-002 / A5 /
 * Principle III). Toggling `ambient_sound_enabled` off OR
 * picking `None` from the dropdown both halt playback while
 * preserving the other field's value (FR-005).
 */
ambient_sound_type?: AmbientSoundType; 
/**
 * Feature 004: output amplitude, 0..=100 inclusive. Clamped at
 * the Settings UI input boundary (`<input type="range" min="0"
 * max="100">`); the audio call site reads the stored value and
 * passes it through to `HtmlAudioElement::set_volume` without
 * re-clamping (Principle III — validate at boundaries only).
 * Default `50` per FR-003 / A9.
 */
ambient_sound_volume?: number }
/**
 * User-entered quick-log entry. Counted by a per-period metric
 * distinct from `completed_pomodoros`; never affects
 * `pomodoros_until_long_break` (FR-027 + SC-005).
 */
export type QuickLog = { 
/**
 * UUID v4 string.
 */
id: string; 
/**
 * User-provided. 1..=120 UTF-8 chars. PII — never log in plain.
 */
title: string; 
/**
 * 1..=720 (1 min to 12 h).
 */
elapsedMinutes: number; 
/**
 * ISO-8601 UTC.
 */
createdAt: string; 
/**
 * chrono `%a %b %d %Y` (e.g. `"Fri May 15 2026"`). Matches the
 * `ManualSession.date` precedent.
 */
date: string }
/**
 * Pomodoro session record persisted in the user's app-data
 * directory. Backend type alias: `PomodoroSession`.
 */
export type Session = { completed_pomodoros: number; 
/**
 * Seconds.
 */
total_focus_time: number; current_session: number; 
/**
 * `%a %b %d %Y` (e.g., "Sat May 10 2026").
 */
date: string; 
/**
 * User-typed session title (≤120 user-perceived chars).
 * `None` for sessions created before this field existed
 * (feature 002), and for in-flight sessions that completed
 * without a typed title. Empty-string is forbidden —
 * normalised to `None` at the capture boundary per Principle
 * III.
 */
title?: string | null }
/**
 * Per-session per-tag time-spent join row.
 * 
 * `duration` is wall-clock seconds spent on this tag during the
 * named session — distinct from `ManualSession::duration` (minutes).
 */
export type SessionTag = { session_id: string; tag_id: string; 
/**
 * Seconds.
 */
duration: number; created_at: string }
/**
 * Closed-domain variant for the `session_type` field on a manual
 * session record (`ManualSession.session_type`).
 * 
 * Wire form: camelCase strings. The `Custom` variant exists on the
 * manual-entry side (user-defined session shapes); the live engine's
 * `TimerMode` has no equivalent.
 */
export type SessionType = "focus" | "break" | "longBreak" | "custom"
/**
 * Full application settings record.
 * 
 * **Wire shape (post-Phase-3a)**: the legacy `hide_status_bar: bool`
 * field is replaced by `status_bar_display: StatusBarDisplay` per
 * the F1/M3 lockstep migration (Phase 3a T150 / T152). Legacy 0.4.x
 * settings JSONs that still carry `hide_status_bar` are read by the
 * `#[serde(from = "SettingsOnDisk")]` shim below: it accepts either
 * shape on the wire, projects through the legacy fallback, and the
 * derived `Serialize` impl then emits only the new shape on next
 * save (legacy field is gone — no field exists for it).
 * 
 * `clippy::struct_excessive_bools` allowance: every bool is an
 * independent settings toggle exposed in the UI; restructuring
 * would not match the JSON shape on disk or the settings page.
 */
export type Settings = { shortcuts: ShortcutSettings; timer: TimerSettings; notifications: NotificationSettings; advanced?: AdvancedSettings; appearance?: AppearanceSettings; autostart: boolean; hide_icon_on_close?: boolean; status_bar_display: StatusBarDisplay; 
/**
 * Update versions the user has dismissed from the update-banner.
 * `#[serde(default)]` so 0.4.x settings JSONs predating this field
 * still deserialise into the cold-start shape.
 */
skipped_versions?: string[] }
/**
 * Keyboard-shortcut bindings bundle.
 * 
 * Each field is `Option<String>` because users can clear a binding
 * (the JS era stores `null` for cleared bindings, which serde maps
 * to `None`). Each string is a Tauri shortcut spec like
 * `"CommandOrControl+Alt+Space"`; parsing happens Rust-side at
 * `register_global_shortcuts` time.
 */
export type ShortcutSettings = { start_stop: string | null; reset: string | null; skip: string | null }
/**
 * Status-bar visibility mode.
 * 
 * Replaces the legacy `hide_status_bar: bool` shape with a typed
 * enum so future "compact" or "hidden" modes don't fork the on-disk
 * encoding.
 * 
 * Wire shape: kebab-case strings (`"default"`, `"icon-only"`),
 * matching the JS-era on-disk values written by
 * `src/managers/settings-manager.js` after its `hide_status_bar →
 * status_bar_display` migration step.
 */
export type StatusBarDisplay = 
/**
 * Full status bar (timer text + icon).
 */
"default" | 
/**
 * Icon-only status bar — corresponds to the legacy
 * `hide_status_bar: true` setting.
 */
"icon-only"
/**
 * User-defined tag attached to sessions and manual entries.
 * 
 * `icon` carries either an emoji or a Remix icon class (e.g.
 * `"ri-briefcase-line"`); `color` is a hex string (e.g. `"#3b82f6"`).
 * Both are pinned to `String` because the JS-era on-disk records mix
 * the two conventions and a closed-domain enum would force a
 * migration (FR-005 — no on-disk shape change).
 */
export type Tag = { id: string; name: string; icon: string; color: string; created_at: string }
/**
 * Task record on the user's task list.
 */
export type Task = { id: string; text: string; completed: boolean; created_at: string; completed_at: string | null }
/**
 * Closed-domain variant for the live-engine session mode.
 * 
 * Wire form: camelCase strings.
 * 
 * Distinct from `SessionType`: `Custom` exists there for manual
 * entries and has no equivalent here — the live engine only runs
 * `Focus`, `Break`, and `LongBreak` per the pomodoro contract.
 */
export type TimerMode = "focus" | "break" | "longBreak"
/**
 * Timer durations & session count.
 * 
 * `weekly_goal_minutes` and `max_session_time` carry
 * `#[serde(default = "...")]` because settings JSON written by
 * pre-widening builds lacks those fields.
 */
export type TimerSettings = { 
/**
 * Minutes.
 */
focus_duration: number; 
/**
 * Minutes.
 */
break_duration: number; 
/**
 * Minutes.
 */
long_break_duration: number; total_sessions: number; weekly_goal_minutes?: number; 
/**
 * Maximum continuous session time before auto-pause (minutes).
 */
max_session_time?: number; 
/**
 * Number of focus completions per long-break cycle (1–10
 * enforced at the Settings UI input boundary, per Principle III).
 * The engine reads this as a configuration input alongside
 * `Durations`; pre-002 settings.json records lacking the field
 * default to `4` (the value previously hard-coded at
 * `src/src/engine/timer.rs:396` and `:831`).
 */
sessions_per_long_break?: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
