
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async saveSessionData(session: Session) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_session_data", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSessionData() : Promise<Result<Session | null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_session_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveTasks(tasks: Task[]) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_tasks", { tasks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadTasks() : Promise<Result<Task[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_tasks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStatsHistory() : Promise<Result<Session[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_stats_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveDailyStats(session: Session) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_daily_stats", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTrayIcon(timerText: string, isRunning: boolean, sessionMode: TimerMode, currentSession: number, totalSessions: number, modeIcon: string | null) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tray_icon", { timerText, isRunning, sessionMode, currentSession, totalSessions, modeIcon }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTrayMenu(isRunning: boolean, isPaused: boolean, currentMode: TimerMode) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tray_menu", { isRunning, isPaused, currentMode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: Settings) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSettings() : Promise<Result<Settings, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerGlobalShortcuts(shortcuts: ShortcutSettings) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_global_shortcuts", { shortcuts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetAllData() : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_all_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startActivityMonitoring(timeoutSeconds: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_activity_monitoring", { timeoutSeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopActivityMonitoring() : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_activity_monitoring") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateActivityTimeout(timeoutSeconds: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_activity_timeout", { timeoutSeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async enableAutostart() : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_autostart") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disableAutostart() : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disable_autostart") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isAutostartEnabled() : Promise<Result<boolean, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_autostart_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveManualSessions(sessions: ManualSession[]) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_manual_sessions", { sessions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadManualSessions() : Promise<Result<ManualSession[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_manual_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadTags() : Promise<Result<Tag[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveTag(tag: Tag) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_tag", { tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTag(tagId: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_tag", { tagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addSessionTag(sessionTag: SessionTag) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_session_tag", { sessionTag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startOauthServer() : Promise<Result<number, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_oauth_server") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supabaseSignInWithPassword(email: string, password: string) : Promise<Result<AuthSession, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supabase_sign_in_with_password", { email, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supabaseSignOut(refreshToken: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supabase_sign_out", { refreshToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supabaseGetSession() : Promise<Result<AuthSession | null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supabase_get_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supabaseRefreshSession(refreshToken: string) : Promise<Result<AuthSession, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supabase_refresh_session", { refreshToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSessionsXlsx(path: string, sessions: ManualSession[]) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_sessions_xlsx", { path, sessions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importLegacySettings(payload: LegacySettingsPayload) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_legacy_settings", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importLegacyHistory(payload: LegacyHistoryPayload) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_legacy_history", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importLegacyTasks(payload: LegacyTasksPayload) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_legacy_tasks", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importLegacyTags(payload: LegacyTagsPayload) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_legacy_tags", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importLegacyManualSessions(payload: LegacyManualSessionsPayload) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_legacy_manual_sessions", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importLegacyUserState(payload: LegacyUserStatePayload) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_legacy_user_state", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importLegacySupabaseSession(payload: SupabaseSessionPayload) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_legacy_supabase_session", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isLegacyMigrationComplete() : Promise<Result<boolean, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_legacy_migration_complete") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markLegacyMigrationComplete() : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_legacy_migration_complete") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Advanced / debug toggles.
 */
export type AdvancedSettings = { debug_mode?: boolean }
/**
 * Appearance / theme preferences.
 * 
 * `theme` is the color-mode preference (`"auto"` / `"light"` /
 * `"dark"`); `timer_theme` is the timer palette stem (e.g.
 * `"espresso"`). Both carry `#[serde(default)]` so pre-widening
 * settings JSONs fill in the JS-era cold-start values.
 */
export type AppearanceSettings = { theme?: string; timer_theme?: string }
/**
 * Supabase auth session record.
 * 
 * Distinct from the pomodoro `Session` by design — both types may
 * be imported at the same call site without conflict (the
 * data-model.md collision note renames this to `AuthSession`).
 */
export type AuthSession = { access_token: string; refresh_token: string; user: AuthUser }
/**
 * Supabase auth user record embedded in `AuthSession`.
 * 
 * `user_metadata` is intentionally `serde_json::Value` (not a typed
 * struct) because Supabase's metadata is open-ended — apps store
 * per-tenant fields like `full_name`, `avatar_url`, OAuth-provider
 * claims, etc. The Leptos consumers (`managers/auth.rs`) read
 * specific keys via `.get("full_name")` rather than imposing a
 * closed shape.
 */
export type AuthUser = { id: string; email: string; user_metadata: JsonValue }
/**
 * Typed error variant returned by every bridge command wrapper.
 * 
 * Wire form is externally-tagged JSON (the `kind` discriminator carries the
 * variant name; data fields sit alongside it).
 */
export type BridgeError = 
/**
 * `window.__TAURI_INTERNALS__` is absent (vite/trunk dev server, e2e
 * mock context). Never produced by the Tauri handler — the Leptos
 * wrapper short-circuits with this variant before calling `invoke()`.
 * Per AGENTS.md §Bridge availability and FR-009.
 */
{ kind: "bridge_unavailable" } | 
/**
 * The caller is in a state where the command is invalid (e.g., a
 * Supabase command without an active session).
 */
{ kind: "not_authenticated" } | 
/**
 * An argument failed validation at the boundary.
 */
{ kind: "invalid_argument"; field: string; reason: string } | 
/**
 * The requested file, key, or row does not exist.
 */
{ kind: "not_found"; resource: string } | 
/**
 * `serde-wasm-bindgen` (or `serde_json`) failed to deserialise the
 * command return on the Leptos side.
 * 
 * Note: data-model.md §`BridgeError` originally specified
 * `command: &'static str` to dodge a per-call allocation, but that
 * makes the enum's `Deserialize` impl require `'de: 'static`, which
 * breaks deserialising any non-static input (e.g., from `from_str`
 * of a heap-allocated JSON buffer). The variant is owning so a
 * `BridgeError` round-trips through serde for every possible
 * discriminant. Allocations are minor (one short literal per failure
 * path; this is the error path, not the hot path).
 */
{ kind: "serde_roundtrip"; command: string; error: string } | 
/**
 * Catch-all for unexpected Tauri-side failures (filesystem errors,
 * plugin errors, etc.). The Tauri-side mapping defaults to this
 * variant for any `.map_err(|e| e.to_string())` call site that
 * lacks semantic context (per data-model.md §`BridgeError` mapping
 * strategy).
 */
{ kind: "internal"; msg: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * JS-era `pomodoro-history` localStorage shape — a vec of `Session`
 * records, the same shape the post-cutover history.json on disk
 * uses (FR-005). Empty vec is the cold-start no-op shape.
 */
export type LegacyHistoryPayload = { history: Session[] }
/**
 * JS-era `presto_manual_sessions` localStorage shape — a vec of
 * `ManualSession` records, identical to the post-cutover
 * `manual_sessions.json` shape on disk.
 */
export type LegacyManualSessionsPayload = { sessions: ManualSession[] }
/**
 * JS-era `pomodoro-settings` localStorage shape, plus the four
 * preference flags split out into separate keys
 * (`theme-preference`, `timer-theme-preference`,
 * `presto_auto_check_updates`).
 * 
 * The core settings JSON shape is identical to the post-cutover
 * `Settings` record (FR-005 — no on-disk shape change), so we
 * reuse `Settings` as the embedded core. The four preference flags
 * are flattened on top because the JS era stored each in its own
 * localStorage key rather than inside the settings JSON; the
 * Tauri-side `import_legacy_settings` handler folds them into the
 * existing `Settings` shape (theme/timer-theme are not yet
 * represented in `Settings` and are dropped on import — they live
 * as user preferences in a later phase, per data-model.md §"Legacy
 * localStorage migration" disposition table).
 */
export type LegacySettingsPayload = { 
/**
 * `pomodoro-settings` localStorage key parsed as the post-cutover
 * `Settings` JSON (FR-005 — round-trip without migration).
 */
settings: Settings | null; 
/**
 * `theme-preference` localStorage key (e.g. `"auto"`, `"dark"`,
 * `"light"`).
 */
theme_preference: string | null; 
/**
 * `timer-theme-preference` localStorage key (e.g. `"espresso"`).
 */
timer_theme_preference: string | null; 
/**
 * `presto_auto_check_updates` localStorage key, parsed as bool.
 */
auto_check_updates: boolean | null }
/**
 * JS-era `presto-tags` localStorage shape — a vec of `Tag` records,
 * identical to the post-cutover `tags.json` shape on disk.
 */
export type LegacyTagsPayload = { tags: Tag[] }
/**
 * JS-era `pomodoro-tasks` localStorage shape — a vec of `Task`
 * records, identical to the post-cutover `tasks.json` shape on disk.
 */
export type LegacyTasksPayload = { tasks: Task[] }
/**
 * JS-era user-state flags.
 * 
 * The boolean / string preferences that live as bare localStorage
 * values rather than inside a JSON blob. Per data-model.md
 * §"Legacy localStorage migration", these fold into the `Settings`
 * user-state slice on the Rust side.
 * 
 * `pomodoro-session` is the active-session snapshot for cross-launch
 * resume (`Session` shape). Carried as `Option<Session>` so the
 * handler can persist it via the existing `save_session_data` path
 * when present.
 */
export type LegacyUserStatePayload = { 
/**
 * `presto-guest-mode` localStorage key, parsed as bool.
 */
guest_mode: boolean | null; 
/**
 * `presto-auth-seen` localStorage key, parsed as bool.
 */
auth_seen: boolean | null; 
/**
 * `presto-skipped-versions` localStorage key — the JS era stored
 * a JSON-encoded `Vec<String>` here. Empty vec when absent.
 */
skipped_versions: string[]; 
/**
 * `pomodoro-session` localStorage key parsed as the post-cutover
 * `Session` shape.
 */
active_session: Session | null }
/**
 * User-entered manual session record.
 * 
 * `session_type` is the closed-domain `SessionType` (was a
 * stringly-typed `String` pre-cutover per spec 001 T029).
 */
export type ManualSession = { id: string; session_type: SessionType; 
/**
 * Minutes.
 */
duration: number; 
/**
 * `HH:MM`.
 */
start_time: string; 
/**
 * `HH:MM`.
 */
end_time: string; notes: string | null; 
/**
 * ISO-8601.
 */
created_at: string; 
/**
 * `%a %b %d %Y`.
 */
date: string; 
/**
 * Inline tag objects per the existing JS-era on-disk shape
 * (FR-005). Loosely typed because legacy records embed full tag
 * objects rather than ID-only references; we normalise at
 * consumption time without reshaping on disk.
 */
tags: JsonValue[] | null; 
/**
 * User-typed session title (≤120 user-perceived chars). Captured
 * at manual-backfill submit time and at natural focus completion
 * (the synth path that mirrors today's auto-saved row into the
 * calendar). Empty-string is forbidden — normalised to `None` at
 * the capture boundary per Principle III.
 */
title?: string | null }
/**
 * Notification preferences.
 * 
 * `auto_start_focus` and `allow_continuous_sessions` carry
 * `#[serde(default)]` because they were added after the `0.4.0`
 * settings shape and may be missing from older settings JSONs.
 * 
 * `clippy::struct_excessive_bools` is silenced because every bool
 * maps to an independent UI toggle; collapsing them into a state
 * machine would not match the on-disk JSON or the settings UI.
 */
export type NotificationSettings = { desktop_notifications: boolean; sound_notifications: boolean; auto_start_timer: boolean; auto_start_focus?: boolean; allow_continuous_sessions?: boolean; smart_pause: boolean; 
/**
 * Seconds.
 */
smart_pause_timeout: number }
/**
 * Pomodoro session record persisted in the user's app-data
 * directory. Backend type alias: `PomodoroSession`.
 */
export type Session = { completed_pomodoros: number; 
/**
 * Seconds.
 */
total_focus_time: number; current_session: number; 
/**
 * `%a %b %d %Y` (e.g., "Sat May 10 2026").
 */
date: string; 
/**
 * User-typed session title (≤120 user-perceived chars).
 * `None` for sessions created before this field existed
 * (feature 002), and for in-flight sessions that completed
 * without a typed title. Empty-string is forbidden —
 * normalised to `None` at the capture boundary per Principle
 * III.
 */
title?: string | null }
/**
 * Per-session per-tag time-spent join row.
 * 
 * `duration` is wall-clock seconds spent on this tag during the
 * named session — distinct from `ManualSession::duration` (minutes).
 */
export type SessionTag = { session_id: string; tag_id: string; 
/**
 * Seconds.
 */
duration: number; created_at: string }
/**
 * Closed-domain variant for the `session_type` field on a manual
 * session record (`ManualSession.session_type`).
 * 
 * Wire form: camelCase strings. The `Custom` variant exists on the
 * manual-entry side (user-defined session shapes); the live engine's
 * `TimerMode` has no equivalent.
 */
export type SessionType = "focus" | "break" | "longBreak" | "custom"
/**
 * Full application settings record.
 * 
 * **Wire shape (post-Phase-3a)**: the legacy `hide_status_bar: bool`
 * field is replaced by `status_bar_display: StatusBarDisplay` per
 * the F1/M3 lockstep migration (Phase 3a T150 / T152). Legacy 0.4.x
 * settings JSONs that still carry `hide_status_bar` are read by the
 * `#[serde(from = "SettingsOnDisk")]` shim below: it accepts either
 * shape on the wire, projects through the legacy fallback, and the
 * derived `Serialize` impl then emits only the new shape on next
 * save (legacy field is gone — no field exists for it).
 * 
 * `clippy::struct_excessive_bools` allowance: every bool is an
 * independent settings toggle exposed in the UI; restructuring
 * would not match the JSON shape on disk or the settings page.
 */
export type Settings = { shortcuts: ShortcutSettings; timer: TimerSettings; notifications: NotificationSettings; advanced?: AdvancedSettings; appearance?: AppearanceSettings; autostart: boolean; analytics_enabled?: boolean; hide_icon_on_close?: boolean; status_bar_display: StatusBarDisplay; 
/**
 * Phase 4e R-002 user-state slice — folded into `Settings` so
 * the JS-era `presto-guest-mode` / `presto-auth-seen` /
 * `presto-skipped-versions` localStorage flags survive cutover.
 * Each field is `#[serde(default)]` so 0.4.x settings JSONs
 * predating this widening still deserialise into the cold-start
 * shape.
 */
guest_mode?: boolean; auth_seen?: boolean; skipped_versions?: string[] }
/**
 * Keyboard-shortcut bindings bundle.
 * 
 * Each field is `Option<String>` because users can clear a binding
 * (the JS era stores `null` for cleared bindings, which serde maps
 * to `None`). Each string is a Tauri shortcut spec like
 * `"CommandOrControl+Alt+Space"`; parsing happens Rust-side at
 * `register_global_shortcuts` time.
 */
export type ShortcutSettings = { start_stop: string | null; reset: string | null; skip: string | null }
/**
 * Status-bar visibility mode.
 * 
 * Replaces the legacy `hide_status_bar: bool` shape with a typed
 * enum so future "compact" or "hidden" modes don't fork the on-disk
 * encoding.
 * 
 * Wire shape: kebab-case strings (`"default"`, `"icon-only"`),
 * matching the JS-era on-disk values written by
 * `src/managers/settings-manager.js` after its `hide_status_bar →
 * status_bar_display` migration step.
 */
export type StatusBarDisplay = 
/**
 * Full status bar (timer text + icon).
 */
"default" | 
/**
 * Icon-only status bar — corresponds to the legacy
 * `hide_status_bar: true` setting.
 */
"icon-only"
/**
 * JS-era Supabase auth token shape persisted at
 * `window.localStorage["sb-<project-ref>-auth-token"]`.
 * 
 * Distinct from `AuthSession` in two ways: (a) it carries
 * `expires_at` (Unix epoch seconds, supabase-js convention) which
 * the Rust-side persisted shape does not yet store, and (b) it is
 * transition-only and slated for removal one minor version after
 * cutover.
 */
export type SupabaseSessionPayload = { access_token: string; refresh_token: string; 
/**
 * Unix epoch seconds, supabase-js convention. Carried for wire
 * fidelity; the Tauri handler ignores it (the post-cutover
 * session re-derives expiry on next refresh).
 */
expires_at: string; user: AuthUser }
/**
 * User-defined tag attached to sessions and manual entries.
 * 
 * `icon` carries either an emoji or a Remix icon class (e.g.
 * `"ri-briefcase-line"`); `color` is a hex string (e.g. `"#3b82f6"`).
 * Both are pinned to `String` because the JS-era on-disk records mix
 * the two conventions and a closed-domain enum would force a
 * migration (FR-005 — no on-disk shape change).
 */
export type Tag = { id: string; name: string; icon: string; color: string; created_at: string }
/**
 * Task record on the user's task list.
 */
export type Task = { id: string; text: string; completed: boolean; created_at: string; completed_at: string | null }
/**
 * Closed-domain variant for the live-engine session mode.
 * 
 * Wire form: camelCase strings.
 * 
 * Distinct from `SessionType`: `Custom` exists there for manual
 * entries and has no equivalent here — the live engine only runs
 * `Focus`, `Break`, and `LongBreak` per the pomodoro contract.
 */
export type TimerMode = "focus" | "break" | "longBreak"
/**
 * Timer durations & session count.
 * 
 * `weekly_goal_minutes` and `max_session_time` carry
 * `#[serde(default = "...")]` because settings JSON written by
 * pre-widening builds lacks those fields.
 */
export type TimerSettings = { 
/**
 * Minutes.
 */
focus_duration: number; 
/**
 * Minutes.
 */
break_duration: number; 
/**
 * Minutes.
 */
long_break_duration: number; total_sessions: number; weekly_goal_minutes?: number; 
/**
 * Maximum continuous session time before auto-pause (minutes).
 */
max_session_time?: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
